### ISSUE TITLE
Spotify App fails with Integration error

### ISSUE THREAD

**Issue by pyriand3r** [tiliado/nuvola-app-spotify#12]
Hi, sorry for reporting so many bugs. Since yesterday nuvola-spotify is not running any more. Nuvola itself starts fine but the spotify app breaks with an integration error:

I have removed and reinstalled nuvola, diorite and apps, removed all cache folders, but the error remains... Any ideas?

Heres a screenshot of the error:

![nuvola_spotify_integration_error](https://cloud.githubusercontent.com/assets/2619815/15497171/a3a7ed4c-2199-11e6-9e09-7a7846ba2944.png)

And here is the debug output: https://gist.github.com/pyriand3r/43c958fbd43507b5d9048ae813e3bbcf

**Comment by fenryxo** [comment]
**This issue has just been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) git branches. Thanks for your bug report.**

At first, this fix will be available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Later, the fix will be also included in the next bug-fix release of the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html).
